### ISSUE TITLE
Code completion doesn't work?

### ISSUE THREAD

**Issue by gnunn1** [WebFreak001/code-d#2]
I had some time and being a bit frustrated with Mono-D's erratic code completion I thought I'd give this a try. I'm currently working on a GtkD project using dub with a dub.json file. Here's the steps I followed to set things up in case I missed anything:

a. Installed visual-studio-code from the Arch AUR package
b. Installed DCD by cloning and building from git
c. Installed dfmt by cloning and building from git
d. Installed workspace-d by cloning and building from git
e. Installed code-d as per instructions on Dlang IDE forum
f. Copied dcd-server, dcd-client, dfmt and workspace-d executables to a location in my path
g. Fired up Visual Code Studio, see settings for DCD server and client in user preferences so assume plugin is installed correctlty
h. Opened the folder containing  my project in Visual Studio Studio, folder contains dub.json
i. Ran ps and verified that workspace-d and dcd-server were running
j. Opened a source code file and attempted code completion by typing '.' after a GtkD class, nothing shows. I get auto-completion in the file for symbols defined in the file. For example, I have a variable called array, start typing arr and array is displayed in popup but that's it.
k. Tried typing 'import std.' expecting to see a list of imports popup but nothing happens

Any tips as to what I am missing here? I am using version 0.10.3 of Visual Studio Code if it helps.

**Comment by WebFreak001** [comment]
I also noticed GtkD imports not working. But `import std.` should work, I need to look into those

**Comment by gnunn1** [comment]
GtkD is broken into sub-projects, so you would need to parse the dub.json for the GtkD package and add imports to DCD for each sub-project if your code is not doing that already.

**Comment by WebFreak001** [comment]
Im using the dub library to fetch import paths. So it should be exactly the same import paths as if you run it with `dub build`

**Comment by gnunn1** [comment]
I found the problem, I mis-configured dcd because the dcd documentation has the configuration file as ~/.config/dcd instead of ~/.config/dcd/dcd.conf. When I ran dcd-server manually it complained about this and once fixed it is working fine. Also, if I manually add the gtk imports to dcd.conf the code completion works fine for gtk, would be nice though if this was picked up automatically. I'm closing this bug for now.

**Comment by WebFreak001** [comment]
good idea, gonna add a warning for that

**Comment by WebFreak001** [comment]
GTK magically started working for me now. I just waited a bit before trying to auto complete. The plugin probably crashes because dcd was not initialized

**Comment by WebFreak001** [comment]
Ok yep that fixed that. Gtk now works without needing to have it in your config. You can remove it from your config if you want faster dcd startup times.

**Comment by gnunn1** [comment]
Thanks, I'll try that.

**Comment by gnunn1** [comment]
Confirmed, works fine if I wait.
