### ISSUE TITLE
Lint interferes with compiler output error messages

### ISSUE THREAD

**Issue by gnunn1** [WebFreak001/code-d#6]
I'm using the tasks I added to the wiki to have my compiler error messages show up in VSCode, however I'm finding that after I fix my first error the linting kicks in and replaces all of the error messages with lint messages (i.e. public method xxx is not documented). Is there a way to disable linting or leave it to the user when to decide to activate it?

**Comment by WebFreak001** [comment]
Oh yes I am definitely planning on adding many more configurations and also on adding dub build as linter. Too bad vscode does not have an api that handles it well. Instead I need to manually wait for a save and set the diagnostics of that file.
