### ISSUE TITLE
Include the text 'dlang' in the plugin description

### ISSUE THREAD

**Issue by TurkeyMan** [WebFreak001/code-d#8]
Make sure `dlang` is present in the extention description so that the filter works properly. This is so users that don't already know what the plugin is called can find it.

In VSCode, if you invoke the `ext install` command, it filters the gigantic list of plugins as you type. If you type `d`, the filter text is not sufficient. Typing `dlang` filters to show other D plugins, but not this one.

**Comment by WebFreak001** [comment]
done
